/*
* generated by Xtext
*/
package org.remus.cmdline.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class CommandLineGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Model");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cProgramsAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cProgramsProgramParserRuleCall_0_0 = (RuleCall)cProgramsAssignment_0.eContents().get(0);
		private final Assignment cSystemAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cSystemSystemParserRuleCall_1_0 = (RuleCall)cSystemAssignment_1.eContents().get(0);
		
		//Model:
		//
		//	programs=Program? system=System?;
		public ParserRule getRule() { return rule; }

		//programs=Program? system=System?
		public Group getGroup() { return cGroup; }

		//programs=Program?
		public Assignment getProgramsAssignment_0() { return cProgramsAssignment_0; }

		//Program
		public RuleCall getProgramsProgramParserRuleCall_0_0() { return cProgramsProgramParserRuleCall_0_0; }

		//system=System?
		public Assignment getSystemAssignment_1() { return cSystemAssignment_1; }

		//System
		public RuleCall getSystemSystemParserRuleCall_1_0() { return cSystemSystemParserRuleCall_1_0; }
	}

	public class SystemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "System");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSystemKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameQualifiedNameParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cPortKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cPortAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cPortIntegerLiteralParserRuleCall_3_1_0 = (RuleCall)cPortAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cVersionKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cVersionAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cVersionStringLiteralParserRuleCall_4_1_0 = (RuleCall)cVersionAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cRegisterProgramKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cProgramAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cProgramProgramCrossReference_5_1_0 = (CrossReference)cProgramAssignment_5_1.eContents().get(0);
		private final RuleCall cProgramProgramIDTerminalRuleCall_5_1_0_1 = (RuleCall)cProgramProgramCrossReference_5_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//System:
		//
		//	"system " name=QualifiedName "{" ("port ->" port=IntegerLiteral)? ("version ->" version=StringLiteral)?
		//
		//	("registerProgram -> " program+=[Program])* "}";
		public ParserRule getRule() { return rule; }

		//"system " name=QualifiedName "{" ("port ->" port=IntegerLiteral)? ("version ->" version=StringLiteral)?
		//
		//("registerProgram -> " program+=[Program])* "}"
		public Group getGroup() { return cGroup; }

		//"system "
		public Keyword getSystemKeyword_0() { return cSystemKeyword_0; }

		//name=QualifiedName
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//QualifiedName
		public RuleCall getNameQualifiedNameParserRuleCall_1_0() { return cNameQualifiedNameParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("port ->" port=IntegerLiteral)?
		public Group getGroup_3() { return cGroup_3; }

		//"port ->"
		public Keyword getPortKeyword_3_0() { return cPortKeyword_3_0; }

		//port=IntegerLiteral
		public Assignment getPortAssignment_3_1() { return cPortAssignment_3_1; }

		//IntegerLiteral
		public RuleCall getPortIntegerLiteralParserRuleCall_3_1_0() { return cPortIntegerLiteralParserRuleCall_3_1_0; }

		//("version ->" version=StringLiteral)?
		public Group getGroup_4() { return cGroup_4; }

		//"version ->"
		public Keyword getVersionKeyword_4_0() { return cVersionKeyword_4_0; }

		//version=StringLiteral
		public Assignment getVersionAssignment_4_1() { return cVersionAssignment_4_1; }

		//StringLiteral
		public RuleCall getVersionStringLiteralParserRuleCall_4_1_0() { return cVersionStringLiteralParserRuleCall_4_1_0; }

		//("registerProgram -> " program+=[Program])*
		public Group getGroup_5() { return cGroup_5; }

		//"registerProgram -> "
		public Keyword getRegisterProgramKeyword_5_0() { return cRegisterProgramKeyword_5_0; }

		//program+=[Program]
		public Assignment getProgramAssignment_5_1() { return cProgramAssignment_5_1; }

		//[Program]
		public CrossReference getProgramProgramCrossReference_5_1_0() { return cProgramProgramCrossReference_5_1_0; }

		//ID
		public RuleCall getProgramProgramIDTerminalRuleCall_5_1_0_1() { return cProgramProgramIDTerminalRuleCall_5_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class ProgramElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Program");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cProgramKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameValidIDParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cPathAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cPathConcatExpressionParserRuleCall_3_0 = (RuleCall)cPathAssignment_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cFunctionsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cFunctionsFunctionParserRuleCall_5_0 = (RuleCall)cFunctionsAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Program:
		//
		//	"program " name=ValidID "->" path=ConcatExpression "{" functions+=Function* "}";
		public ParserRule getRule() { return rule; }

		//"program " name=ValidID "->" path=ConcatExpression "{" functions+=Function* "}"
		public Group getGroup() { return cGroup; }

		//"program "
		public Keyword getProgramKeyword_0() { return cProgramKeyword_0; }

		//name=ValidID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ValidID
		public RuleCall getNameValidIDParserRuleCall_1_0() { return cNameValidIDParserRuleCall_1_0; }

		//"->"
		public Keyword getHyphenMinusGreaterThanSignKeyword_2() { return cHyphenMinusGreaterThanSignKeyword_2; }

		//path=ConcatExpression
		public Assignment getPathAssignment_3() { return cPathAssignment_3; }

		//ConcatExpression
		public RuleCall getPathConcatExpressionParserRuleCall_3_0() { return cPathConcatExpressionParserRuleCall_3_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }

		//functions+=Function*
		public Assignment getFunctionsAssignment_5() { return cFunctionsAssignment_5; }

		//Function
		public RuleCall getFunctionsFunctionParserRuleCall_5_0() { return cFunctionsFunctionParserRuleCall_5_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class ParamElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Param");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNameValidIDParserRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//Param:
		//
		//	name=ValidID;
		public ParserRule getRule() { return rule; }

		//name=ValidID
		public Assignment getNameAssignment() { return cNameAssignment; }

		//ValidID
		public RuleCall getNameValidIDParserRuleCall_0() { return cNameValidIDParserRuleCall_0; }
	}

	public class FunctionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Function");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDefKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cWithKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cPrintOutModeAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cPrintOutModePrintModeEnumRuleCall_2_1_0 = (RuleCall)cPrintOutModeAssignment_2_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDescKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDescAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDescStringLiteralParserRuleCall_4_1_0 = (RuleCall)cDescAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cDocurlKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cDocurlAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cDocurlStringLiteralParserRuleCall_5_1_0 = (RuleCall)cDocurlAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cInputKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cInputAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cInputInputDataDefinitionParserRuleCall_6_1_0 = (RuleCall)cInputAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cOutputKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cOutputAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cOutputOutputDataDefinitionParserRuleCall_7_1_0 = (RuleCall)cOutputAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cAsteriskSpaceKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cOptionBlocksAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cOptionBlocksOptionParserRuleCall_8_1_0 = (RuleCall)cOptionBlocksAssignment_8_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Function:
		//
		//	"def" name=ID ("with " printOutMode=PrintMode)? "{" ("desc ->" desc=StringLiteral)? ("docurl ->"
		//
		//	docurl=StringLiteral)? ("input" input+=InputDataDefinition)* ("output " output+=OutputDataDefinition)* ("* "
		//
		//	optionBlocks+=Option)* "}";
		public ParserRule getRule() { return rule; }

		//"def" name=ID ("with " printOutMode=PrintMode)? "{" ("desc ->" desc=StringLiteral)? ("docurl ->" docurl=StringLiteral)?
		//
		//("input" input+=InputDataDefinition)* ("output " output+=OutputDataDefinition)* ("* " optionBlocks+=Option)* "}"
		public Group getGroup() { return cGroup; }

		//"def"
		public Keyword getDefKeyword_0() { return cDefKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//("with " printOutMode=PrintMode)?
		public Group getGroup_2() { return cGroup_2; }

		//"with "
		public Keyword getWithKeyword_2_0() { return cWithKeyword_2_0; }

		//printOutMode=PrintMode
		public Assignment getPrintOutModeAssignment_2_1() { return cPrintOutModeAssignment_2_1; }

		//PrintMode
		public RuleCall getPrintOutModePrintModeEnumRuleCall_2_1_0() { return cPrintOutModePrintModeEnumRuleCall_2_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("desc ->" desc=StringLiteral)?
		public Group getGroup_4() { return cGroup_4; }

		//"desc ->"
		public Keyword getDescKeyword_4_0() { return cDescKeyword_4_0; }

		//desc=StringLiteral
		public Assignment getDescAssignment_4_1() { return cDescAssignment_4_1; }

		//StringLiteral
		public RuleCall getDescStringLiteralParserRuleCall_4_1_0() { return cDescStringLiteralParserRuleCall_4_1_0; }

		//("docurl ->" docurl=StringLiteral)?
		public Group getGroup_5() { return cGroup_5; }

		//"docurl ->"
		public Keyword getDocurlKeyword_5_0() { return cDocurlKeyword_5_0; }

		//docurl=StringLiteral
		public Assignment getDocurlAssignment_5_1() { return cDocurlAssignment_5_1; }

		//StringLiteral
		public RuleCall getDocurlStringLiteralParserRuleCall_5_1_0() { return cDocurlStringLiteralParserRuleCall_5_1_0; }

		//("input" input+=InputDataDefinition)*
		public Group getGroup_6() { return cGroup_6; }

		//"input"
		public Keyword getInputKeyword_6_0() { return cInputKeyword_6_0; }

		//input+=InputDataDefinition
		public Assignment getInputAssignment_6_1() { return cInputAssignment_6_1; }

		//InputDataDefinition
		public RuleCall getInputInputDataDefinitionParserRuleCall_6_1_0() { return cInputInputDataDefinitionParserRuleCall_6_1_0; }

		//("output " output+=OutputDataDefinition)*
		public Group getGroup_7() { return cGroup_7; }

		//"output "
		public Keyword getOutputKeyword_7_0() { return cOutputKeyword_7_0; }

		//output+=OutputDataDefinition
		public Assignment getOutputAssignment_7_1() { return cOutputAssignment_7_1; }

		//OutputDataDefinition
		public RuleCall getOutputOutputDataDefinitionParserRuleCall_7_1_0() { return cOutputOutputDataDefinitionParserRuleCall_7_1_0; }

		//("* " optionBlocks+=Option)*
		public Group getGroup_8() { return cGroup_8; }

		//"* "
		public Keyword getAsteriskSpaceKeyword_8_0() { return cAsteriskSpaceKeyword_8_0; }

		//optionBlocks+=Option
		public Assignment getOptionBlocksAssignment_8_1() { return cOptionBlocksAssignment_8_1; }

		//Option
		public RuleCall getOptionBlocksOptionParserRuleCall_8_1_0() { return cOptionBlocksOptionParserRuleCall_8_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}

	public class InputDataDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "InputDataDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cInputDataDefinitionAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cInputAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cInputParamParserRuleCall_1_0 = (RuleCall)cInputAssignment_1.eContents().get(0);
		private final Keyword cAsKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTypeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTypeInputDataTypeEnumRuleCall_3_0 = (RuleCall)cTypeAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDocKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDocAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDocStringLiteralParserRuleCall_4_1_0 = (RuleCall)cDocAssignment_4_1.eContents().get(0);
		
		//InputDataDefinition:
		//
		//	{InputDataDefinition} input=Param "as" type=InputDataType ("doc -> " doc=StringLiteral)?;
		public ParserRule getRule() { return rule; }

		//{InputDataDefinition} input=Param "as" type=InputDataType ("doc -> " doc=StringLiteral)?
		public Group getGroup() { return cGroup; }

		//{InputDataDefinition}
		public Action getInputDataDefinitionAction_0() { return cInputDataDefinitionAction_0; }

		//input=Param
		public Assignment getInputAssignment_1() { return cInputAssignment_1; }

		//Param
		public RuleCall getInputParamParserRuleCall_1_0() { return cInputParamParserRuleCall_1_0; }

		//"as"
		public Keyword getAsKeyword_2() { return cAsKeyword_2; }

		//type=InputDataType
		public Assignment getTypeAssignment_3() { return cTypeAssignment_3; }

		//InputDataType
		public RuleCall getTypeInputDataTypeEnumRuleCall_3_0() { return cTypeInputDataTypeEnumRuleCall_3_0; }

		//("doc -> " doc=StringLiteral)?
		public Group getGroup_4() { return cGroup_4; }

		//"doc -> "
		public Keyword getDocKeyword_4_0() { return cDocKeyword_4_0; }

		//doc=StringLiteral
		public Assignment getDocAssignment_4_1() { return cDocAssignment_4_1; }

		//StringLiteral
		public RuleCall getDocStringLiteralParserRuleCall_4_1_0() { return cDocStringLiteralParserRuleCall_4_1_0; }
	}

	public class OutputDataDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "OutputDataDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cOutputDataDefinitionAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cInputAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cInputParamParserRuleCall_1_0 = (RuleCall)cInputAssignment_1.eContents().get(0);
		private final Keyword cAsKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTypeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTypeOutputDataTypeEnumRuleCall_3_0 = (RuleCall)cTypeAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDocKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDocAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDocStringLiteralParserRuleCall_4_1_0 = (RuleCall)cDocAssignment_4_1.eContents().get(0);
		
		//OutputDataDefinition:
		//
		//	{OutputDataDefinition} input=Param "as" type=OutputDataType ("doc -> " doc=StringLiteral)?;
		public ParserRule getRule() { return rule; }

		//{OutputDataDefinition} input=Param "as" type=OutputDataType ("doc -> " doc=StringLiteral)?
		public Group getGroup() { return cGroup; }

		//{OutputDataDefinition}
		public Action getOutputDataDefinitionAction_0() { return cOutputDataDefinitionAction_0; }

		//input=Param
		public Assignment getInputAssignment_1() { return cInputAssignment_1; }

		//Param
		public RuleCall getInputParamParserRuleCall_1_0() { return cInputParamParserRuleCall_1_0; }

		//"as"
		public Keyword getAsKeyword_2() { return cAsKeyword_2; }

		//type=OutputDataType
		public Assignment getTypeAssignment_3() { return cTypeAssignment_3; }

		//OutputDataType
		public RuleCall getTypeOutputDataTypeEnumRuleCall_3_0() { return cTypeOutputDataTypeEnumRuleCall_3_0; }

		//("doc -> " doc=StringLiteral)?
		public Group getGroup_4() { return cGroup_4; }

		//"doc -> "
		public Keyword getDocKeyword_4_0() { return cDocKeyword_4_0; }

		//doc=StringLiteral
		public Assignment getDocAssignment_4_1() { return cDocAssignment_4_1; }

		//StringLiteral
		public RuleCall getDocStringLiteralParserRuleCall_4_1_0() { return cDocStringLiteralParserRuleCall_4_1_0; }
	}

	public class OptionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Option");
		private final Assignment cParamAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cParamConcatExpressionParserRuleCall_0 = (RuleCall)cParamAssignment.eContents().get(0);
		
		//Option:
		//
		//	param=ConcatExpression;
		public ParserRule getRule() { return rule; }

		//param=ConcatExpression
		public Assignment getParamAssignment() { return cParamAssignment; }

		//ConcatExpression
		public RuleCall getParamConcatExpressionParserRuleCall_0() { return cParamConcatExpressionParserRuleCall_0; }
	}

	public class ConcatExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ConcatExpression");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cPrimaryParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cConcatenationLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cPlusSignKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightPrimaryParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//ConcatExpression returns Expression:
		//
		//	Primary ({Concatenation.left=current} "+" right=Primary)*;
		public ParserRule getRule() { return rule; }

		//Primary ({Concatenation.left=current} "+" right=Primary)*
		public Group getGroup() { return cGroup; }

		//Primary
		public RuleCall getPrimaryParserRuleCall_0() { return cPrimaryParserRuleCall_0; }

		//({Concatenation.left=current} "+" right=Primary)*
		public Group getGroup_1() { return cGroup_1; }

		//{Concatenation.left=current}
		public Action getConcatenationLeftAction_1_0() { return cConcatenationLeftAction_1_0; }

		//"+"
		public Keyword getPlusSignKeyword_1_1() { return cPlusSignKeyword_1_1; }

		//right=Primary
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }

		//Primary
		public RuleCall getRightPrimaryParserRuleCall_1_2_0() { return cRightPrimaryParserRuleCall_1_2_0; }
	}

	public class StringLiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "StringLiteral");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueSTRINGTerminalRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//StringLiteral:
		//
		//	value=STRING;
		public ParserRule getRule() { return rule; }

		//value=STRING
		public Assignment getValueAssignment() { return cValueAssignment; }

		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_0() { return cValueSTRINGTerminalRuleCall_0; }
	}

	public class IntegerLiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "IntegerLiteral");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueINTTerminalRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//IntegerLiteral:
		//
		//	value=INT;
		public ParserRule getRule() { return rule; }

		//value=INT
		public Assignment getValueAssignment() { return cValueAssignment; }

		//INT
		public RuleCall getValueINTTerminalRuleCall_0() { return cValueINTTerminalRuleCall_0; }
	}

	public class DoubleLiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "DoubleLiteral");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cValueAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cValueINTTerminalRuleCall_0_0 = (RuleCall)cValueAssignment_0.eContents().get(0);
		private final Keyword cFullStopKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		
		//DoubleLiteral:
		//
		//	value=INT "." INT;
		public ParserRule getRule() { return rule; }

		//value=INT "." INT
		public Group getGroup() { return cGroup; }

		//value=INT
		public Assignment getValueAssignment_0() { return cValueAssignment_0; }

		//INT
		public RuleCall getValueINTTerminalRuleCall_0_0() { return cValueINTTerminalRuleCall_0_0; }

		//"."
		public Keyword getFullStopKeyword_1() { return cFullStopKeyword_1; }

		//INT
		public RuleCall getINTTerminalRuleCall_2() { return cINTTerminalRuleCall_2; }
	}

	public class QualifiedNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "QualifiedName");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cValidIDParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cValidIDParserRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//QualifiedName:
		//
		//	ValidID ("." ValidID)*;
		public ParserRule getRule() { return rule; }

		//ValidID ("." ValidID)*
		public Group getGroup() { return cGroup; }

		//ValidID
		public RuleCall getValidIDParserRuleCall_0() { return cValidIDParserRuleCall_0; }

		//("." ValidID)*
		public Group getGroup_1() { return cGroup_1; }

		//"."
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }

		//ValidID
		public RuleCall getValidIDParserRuleCall_1_1() { return cValidIDParserRuleCall_1_1; }
	}

	public class ValidIDElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ValidID");
		private final RuleCall cIDTerminalRuleCall = (RuleCall)rule.eContents().get(1);
		
		//ValidID:
		//
		//	ID;
		public ParserRule getRule() { return rule; }

		//ID
		public RuleCall getIDTerminalRuleCall() { return cIDTerminalRuleCall; }
	}

	public class PrimaryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Primary");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cStringLiteralParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIntegerLiteralParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cDoubleLiteralParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final Assignment cParamAssignment_3 = (Assignment)cAlternatives.eContents().get(3);
		private final CrossReference cParamParamCrossReference_3_0 = (CrossReference)cParamAssignment_3.eContents().get(0);
		private final RuleCall cParamParamIDTerminalRuleCall_3_0_1 = (RuleCall)cParamParamCrossReference_3_0.eContents().get(1);
		
		//Primary returns Expression:
		//
		//	StringLiteral | IntegerLiteral | DoubleLiteral | param=[Param];
		public ParserRule getRule() { return rule; }

		//StringLiteral | IntegerLiteral | DoubleLiteral | param=[Param]
		public Alternatives getAlternatives() { return cAlternatives; }

		//StringLiteral
		public RuleCall getStringLiteralParserRuleCall_0() { return cStringLiteralParserRuleCall_0; }

		//IntegerLiteral
		public RuleCall getIntegerLiteralParserRuleCall_1() { return cIntegerLiteralParserRuleCall_1; }

		//DoubleLiteral
		public RuleCall getDoubleLiteralParserRuleCall_2() { return cDoubleLiteralParserRuleCall_2; }

		//param=[Param]
		public Assignment getParamAssignment_3() { return cParamAssignment_3; }

		//[Param]
		public CrossReference getParamParamCrossReference_3_0() { return cParamParamCrossReference_3_0; }

		//ID
		public RuleCall getParamParamIDTerminalRuleCall_3_0_1() { return cParamParamIDTerminalRuleCall_3_0_1; }
	}
	
	
	public class PrintModeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "PrintMode");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cSTDOUTEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cSTDOUTSTDOUTKeyword_0_0 = (Keyword)cSTDOUTEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cSTDERREnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cSTDERRSTDERRKeyword_1_0 = (Keyword)cSTDERREnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cBOTHEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cBOTHBOTHKeyword_2_0 = (Keyword)cBOTHEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum PrintMode:
		//
		//	STDOUT | STDERR | BOTH;
		public EnumRule getRule() { return rule; }

		//STDOUT | STDERR | BOTH
		public Alternatives getAlternatives() { return cAlternatives; }

		//STDOUT
		public EnumLiteralDeclaration getSTDOUTEnumLiteralDeclaration_0() { return cSTDOUTEnumLiteralDeclaration_0; }

		//"STDOUT"
		public Keyword getSTDOUTSTDOUTKeyword_0_0() { return cSTDOUTSTDOUTKeyword_0_0; }

		//STDERR
		public EnumLiteralDeclaration getSTDERREnumLiteralDeclaration_1() { return cSTDERREnumLiteralDeclaration_1; }

		//"STDERR"
		public Keyword getSTDERRSTDERRKeyword_1_0() { return cSTDERRSTDERRKeyword_1_0; }

		//BOTH
		public EnumLiteralDeclaration getBOTHEnumLiteralDeclaration_2() { return cBOTHEnumLiteralDeclaration_2; }

		//"BOTH"
		public Keyword getBOTHBOTHKeyword_2_0() { return cBOTHBOTHKeyword_2_0; }
	}

	public class InputDataTypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "InputDataType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cSTRINGEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cSTRINGSTRINGKeyword_0_0 = (Keyword)cSTRINGEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cPATHEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cPATHPATHKeyword_1_0 = (Keyword)cPATHEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum InputDataType:
		//
		//	STRING | PATH;
		public EnumRule getRule() { return rule; }

		//STRING | PATH
		public Alternatives getAlternatives() { return cAlternatives; }

		//STRING
		public EnumLiteralDeclaration getSTRINGEnumLiteralDeclaration_0() { return cSTRINGEnumLiteralDeclaration_0; }

		//"STRING"
		public Keyword getSTRINGSTRINGKeyword_0_0() { return cSTRINGSTRINGKeyword_0_0; }

		//PATH
		public EnumLiteralDeclaration getPATHEnumLiteralDeclaration_1() { return cPATHEnumLiteralDeclaration_1; }

		//"PATH"
		public Keyword getPATHPATHKeyword_1_0() { return cPATHPATHKeyword_1_0; }
	}

	public class OutputDataTypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "OutputDataType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cPATHEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cPATHPATHKeyword_0_0 = (Keyword)cPATHEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cFOLDERPATHEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cFOLDERPATHFOLDERPATHKeyword_1_0 = (Keyword)cFOLDERPATHEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum OutputDataType:
		//
		//	PATH | FOLDERPATH;
		public EnumRule getRule() { return rule; }

		//PATH | FOLDERPATH
		public Alternatives getAlternatives() { return cAlternatives; }

		//PATH
		public EnumLiteralDeclaration getPATHEnumLiteralDeclaration_0() { return cPATHEnumLiteralDeclaration_0; }

		//"PATH"
		public Keyword getPATHPATHKeyword_0_0() { return cPATHPATHKeyword_0_0; }

		//FOLDERPATH
		public EnumLiteralDeclaration getFOLDERPATHEnumLiteralDeclaration_1() { return cFOLDERPATHEnumLiteralDeclaration_1; }

		//"FOLDERPATH"
		public Keyword getFOLDERPATHFOLDERPATHKeyword_1_0() { return cFOLDERPATHFOLDERPATHKeyword_1_0; }
	}
	
	private ModelElements pModel;
	private SystemElements pSystem;
	private ProgramElements pProgram;
	private ParamElements pParam;
	private FunctionElements pFunction;
	private InputDataDefinitionElements pInputDataDefinition;
	private OutputDataDefinitionElements pOutputDataDefinition;
	private PrintModeElements unknownRulePrintMode;
	private InputDataTypeElements unknownRuleInputDataType;
	private OutputDataTypeElements unknownRuleOutputDataType;
	private OptionElements pOption;
	private ConcatExpressionElements pConcatExpression;
	private StringLiteralElements pStringLiteral;
	private IntegerLiteralElements pIntegerLiteral;
	private DoubleLiteralElements pDoubleLiteral;
	private QualifiedNameElements pQualifiedName;
	private ValidIDElements pValidID;
	private PrimaryElements pPrimary;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public CommandLineGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.remus.cmdline.CommandLine".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//
	//	programs=Program? system=System?;
	public ModelElements getModelAccess() {
		return (pModel != null) ? pModel : (pModel = new ModelElements());
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}

	//System:
	//
	//	"system " name=QualifiedName "{" ("port ->" port=IntegerLiteral)? ("version ->" version=StringLiteral)?
	//
	//	("registerProgram -> " program+=[Program])* "}";
	public SystemElements getSystemAccess() {
		return (pSystem != null) ? pSystem : (pSystem = new SystemElements());
	}
	
	public ParserRule getSystemRule() {
		return getSystemAccess().getRule();
	}

	//Program:
	//
	//	"program " name=ValidID "->" path=ConcatExpression "{" functions+=Function* "}";
	public ProgramElements getProgramAccess() {
		return (pProgram != null) ? pProgram : (pProgram = new ProgramElements());
	}
	
	public ParserRule getProgramRule() {
		return getProgramAccess().getRule();
	}

	//Param:
	//
	//	name=ValidID;
	public ParamElements getParamAccess() {
		return (pParam != null) ? pParam : (pParam = new ParamElements());
	}
	
	public ParserRule getParamRule() {
		return getParamAccess().getRule();
	}

	//Function:
	//
	//	"def" name=ID ("with " printOutMode=PrintMode)? "{" ("desc ->" desc=StringLiteral)? ("docurl ->"
	//
	//	docurl=StringLiteral)? ("input" input+=InputDataDefinition)* ("output " output+=OutputDataDefinition)* ("* "
	//
	//	optionBlocks+=Option)* "}";
	public FunctionElements getFunctionAccess() {
		return (pFunction != null) ? pFunction : (pFunction = new FunctionElements());
	}
	
	public ParserRule getFunctionRule() {
		return getFunctionAccess().getRule();
	}

	//InputDataDefinition:
	//
	//	{InputDataDefinition} input=Param "as" type=InputDataType ("doc -> " doc=StringLiteral)?;
	public InputDataDefinitionElements getInputDataDefinitionAccess() {
		return (pInputDataDefinition != null) ? pInputDataDefinition : (pInputDataDefinition = new InputDataDefinitionElements());
	}
	
	public ParserRule getInputDataDefinitionRule() {
		return getInputDataDefinitionAccess().getRule();
	}

	//OutputDataDefinition:
	//
	//	{OutputDataDefinition} input=Param "as" type=OutputDataType ("doc -> " doc=StringLiteral)?;
	public OutputDataDefinitionElements getOutputDataDefinitionAccess() {
		return (pOutputDataDefinition != null) ? pOutputDataDefinition : (pOutputDataDefinition = new OutputDataDefinitionElements());
	}
	
	public ParserRule getOutputDataDefinitionRule() {
		return getOutputDataDefinitionAccess().getRule();
	}

	//enum PrintMode:
	//
	//	STDOUT | STDERR | BOTH;
	public PrintModeElements getPrintModeAccess() {
		return (unknownRulePrintMode != null) ? unknownRulePrintMode : (unknownRulePrintMode = new PrintModeElements());
	}
	
	public EnumRule getPrintModeRule() {
		return getPrintModeAccess().getRule();
	}

	//enum InputDataType:
	//
	//	STRING | PATH;
	public InputDataTypeElements getInputDataTypeAccess() {
		return (unknownRuleInputDataType != null) ? unknownRuleInputDataType : (unknownRuleInputDataType = new InputDataTypeElements());
	}
	
	public EnumRule getInputDataTypeRule() {
		return getInputDataTypeAccess().getRule();
	}

	//enum OutputDataType:
	//
	//	PATH | FOLDERPATH;
	public OutputDataTypeElements getOutputDataTypeAccess() {
		return (unknownRuleOutputDataType != null) ? unknownRuleOutputDataType : (unknownRuleOutputDataType = new OutputDataTypeElements());
	}
	
	public EnumRule getOutputDataTypeRule() {
		return getOutputDataTypeAccess().getRule();
	}

	//Option:
	//
	//	param=ConcatExpression;
	public OptionElements getOptionAccess() {
		return (pOption != null) ? pOption : (pOption = new OptionElements());
	}
	
	public ParserRule getOptionRule() {
		return getOptionAccess().getRule();
	}

	//ConcatExpression returns Expression:
	//
	//	Primary ({Concatenation.left=current} "+" right=Primary)*;
	public ConcatExpressionElements getConcatExpressionAccess() {
		return (pConcatExpression != null) ? pConcatExpression : (pConcatExpression = new ConcatExpressionElements());
	}
	
	public ParserRule getConcatExpressionRule() {
		return getConcatExpressionAccess().getRule();
	}

	//StringLiteral:
	//
	//	value=STRING;
	public StringLiteralElements getStringLiteralAccess() {
		return (pStringLiteral != null) ? pStringLiteral : (pStringLiteral = new StringLiteralElements());
	}
	
	public ParserRule getStringLiteralRule() {
		return getStringLiteralAccess().getRule();
	}

	//IntegerLiteral:
	//
	//	value=INT;
	public IntegerLiteralElements getIntegerLiteralAccess() {
		return (pIntegerLiteral != null) ? pIntegerLiteral : (pIntegerLiteral = new IntegerLiteralElements());
	}
	
	public ParserRule getIntegerLiteralRule() {
		return getIntegerLiteralAccess().getRule();
	}

	//DoubleLiteral:
	//
	//	value=INT "." INT;
	public DoubleLiteralElements getDoubleLiteralAccess() {
		return (pDoubleLiteral != null) ? pDoubleLiteral : (pDoubleLiteral = new DoubleLiteralElements());
	}
	
	public ParserRule getDoubleLiteralRule() {
		return getDoubleLiteralAccess().getRule();
	}

	//QualifiedName:
	//
	//	ValidID ("." ValidID)*;
	public QualifiedNameElements getQualifiedNameAccess() {
		return (pQualifiedName != null) ? pQualifiedName : (pQualifiedName = new QualifiedNameElements());
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}

	//ValidID:
	//
	//	ID;
	public ValidIDElements getValidIDAccess() {
		return (pValidID != null) ? pValidID : (pValidID = new ValidIDElements());
	}
	
	public ParserRule getValidIDRule() {
		return getValidIDAccess().getRule();
	}

	//Primary returns Expression:
	//
	//	StringLiteral | IntegerLiteral | DoubleLiteral | param=[Param];
	public PrimaryElements getPrimaryAccess() {
		return (pPrimary != null) ? pPrimary : (pPrimary = new PrimaryElements());
	}
	
	public ParserRule getPrimaryRule() {
		return getPrimaryAccess().getRule();
	}

	//terminal ID:
	//
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
