<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="commandLine" nsURI="http://www.remus-software.org/cmdline/1.0"
    nsPrefix="commandLine">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="programs" eType="#//Program"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="system" eType="#//System"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="System">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" eType="#//IntegerLiteral"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="version" eType="#//StringLiteral"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="program" unique="false"
        upperBound="-1" eType="#//Program"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Program">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="path" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="functions" upperBound="-1"
        eType="#//Function" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Param">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Function">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="printOutMode" eType="#//PrintMode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="desc" eType="#//StringLiteral"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="docurl" eType="#//StringLiteral"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" upperBound="-1"
        eType="#//InputDataDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" upperBound="-1"
        eType="#//OutputDataDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="optionBlocks" upperBound="-1"
        eType="#//Option" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputDataDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" eType="#//Param"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//InputDataType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doc" eType="#//StringLiteral"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputDataDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" eType="#//Param"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//OutputDataType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doc" eType="#//StringLiteral"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PrintMode">
    <eLiterals name="STDOUT" literal="STDOUT"/>
    <eLiterals name="STDERR" value="1" literal="STDERR"/>
    <eLiterals name="BOTH" value="2" literal="BOTH"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="InputDataType">
    <eLiterals name="STRING" literal="STRING"/>
    <eLiterals name="PATH" value="1" literal="PATH"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OutputDataType">
    <eLiterals name="PATH" literal="PATH"/>
    <eLiterals name="FOLDERPATH" value="1" literal="FOLDERPATH"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Option">
    <eStructuralFeatures xsi:type="ecore:EReference" name="param" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="param" eType="#//Param"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringLiteral" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerLiteral" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoubleLiteral" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Concatenation" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
