/*
* generated by Xtext
*/
package org.remus.cmdline.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.remus.cmdline.services.CommandLineGrammarAccess;

public class CommandLineParser extends AbstractContentAssistParser {
	
	@Inject
	private CommandLineGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.remus.cmdline.ui.contentassist.antlr.internal.InternalCommandLineParser createParser() {
		org.remus.cmdline.ui.contentassist.antlr.internal.InternalCommandLineParser result = new org.remus.cmdline.ui.contentassist.antlr.internal.InternalCommandLineParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getPrimaryAccess().getAlternatives(), "rule__Primary__Alternatives");
					put(grammarAccess.getDataTypeAccess().getAlternatives(), "rule__DataType__Alternatives");
					put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
					put(grammarAccess.getProgramAccess().getGroup(), "rule__Program__Group__0");
					put(grammarAccess.getFunctionAccess().getGroup(), "rule__Function__Group__0");
					put(grammarAccess.getFunctionAccess().getGroup_3(), "rule__Function__Group_3__0");
					put(grammarAccess.getFunctionAccess().getGroup_4(), "rule__Function__Group_4__0");
					put(grammarAccess.getFunctionAccess().getGroup_5(), "rule__Function__Group_5__0");
					put(grammarAccess.getFunctionAccess().getGroup_6(), "rule__Function__Group_6__0");
					put(grammarAccess.getFunctionAccess().getGroup_7(), "rule__Function__Group_7__0");
					put(grammarAccess.getDataDefinitionAccess().getGroup(), "rule__DataDefinition__Group__0");
					put(grammarAccess.getDataDefinitionAccess().getGroup_4(), "rule__DataDefinition__Group_4__0");
					put(grammarAccess.getConcatExpressionAccess().getGroup(), "rule__ConcatExpression__Group__0");
					put(grammarAccess.getConcatExpressionAccess().getGroup_1(), "rule__ConcatExpression__Group_1__0");
					put(grammarAccess.getDoubleLiteralAccess().getGroup(), "rule__DoubleLiteral__Group__0");
					put(grammarAccess.getImportAccess().getGroup(), "rule__Import__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
					put(grammarAccess.getModelAccess().getImportsAssignment_0(), "rule__Model__ImportsAssignment_0");
					put(grammarAccess.getModelAccess().getProgramsAssignment_1(), "rule__Model__ProgramsAssignment_1");
					put(grammarAccess.getProgramAccess().getNameAssignment_1(), "rule__Program__NameAssignment_1");
					put(grammarAccess.getProgramAccess().getPathAssignment_3(), "rule__Program__PathAssignment_3");
					put(grammarAccess.getProgramAccess().getFunctionsAssignment_5(), "rule__Program__FunctionsAssignment_5");
					put(grammarAccess.getParamAccess().getNameAssignment(), "rule__Param__NameAssignment");
					put(grammarAccess.getFunctionAccess().getNameAssignment_1(), "rule__Function__NameAssignment_1");
					put(grammarAccess.getFunctionAccess().getDescAssignment_3_1(), "rule__Function__DescAssignment_3_1");
					put(grammarAccess.getFunctionAccess().getDocurlAssignment_4_1(), "rule__Function__DocurlAssignment_4_1");
					put(grammarAccess.getFunctionAccess().getInputAssignment_5_1(), "rule__Function__InputAssignment_5_1");
					put(grammarAccess.getFunctionAccess().getOutputAssignment_6_1(), "rule__Function__OutputAssignment_6_1");
					put(grammarAccess.getFunctionAccess().getOptionBlocksAssignment_7_1(), "rule__Function__OptionBlocksAssignment_7_1");
					put(grammarAccess.getDataDefinitionAccess().getInputAssignment_1(), "rule__DataDefinition__InputAssignment_1");
					put(grammarAccess.getDataDefinitionAccess().getTypeAssignment_3(), "rule__DataDefinition__TypeAssignment_3");
					put(grammarAccess.getDataDefinitionAccess().getDocAssignment_4_1(), "rule__DataDefinition__DocAssignment_4_1");
					put(grammarAccess.getOptionAccess().getParamAssignment(), "rule__Option__ParamAssignment");
					put(grammarAccess.getConcatExpressionAccess().getRightAssignment_1_2(), "rule__ConcatExpression__RightAssignment_1_2");
					put(grammarAccess.getStringLiteralAccess().getValueAssignment(), "rule__StringLiteral__ValueAssignment");
					put(grammarAccess.getIntegerLiteralAccess().getValueAssignment(), "rule__IntegerLiteral__ValueAssignment");
					put(grammarAccess.getDoubleLiteralAccess().getValueAssignment_0(), "rule__DoubleLiteral__ValueAssignment_0");
					put(grammarAccess.getImportAccess().getImportURIAssignment_1(), "rule__Import__ImportURIAssignment_1");
					put(grammarAccess.getPrimaryAccess().getParamAssignment_3(), "rule__Primary__ParamAssignment_3");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.remus.cmdline.ui.contentassist.antlr.internal.InternalCommandLineParser typedParser = (org.remus.cmdline.ui.contentassist.antlr.internal.InternalCommandLineParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public CommandLineGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(CommandLineGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
