/*
 * generated by Xtext
 */
package org.remus.cmdline.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractCommandLineValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.remus.cmdline.commandLine.CommandLinePackage.eINSTANCE);
		return result;
	}
}
