/*
* generated by Xtext
*/
package org.remus.cmdline.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.remus.cmdline.services.CommandLineGrammarAccess;

public class CommandLineParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private CommandLineGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.remus.cmdline.parser.antlr.internal.InternalCommandLineParser createParser(XtextTokenStream stream) {
		return new org.remus.cmdline.parser.antlr.internal.InternalCommandLineParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public CommandLineGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(CommandLineGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
