/*
 * generated by Xtext
 */
package org.remus.cmdline.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.remus.cmdline.ui.internal.CommandLineActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CommandLineExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return CommandLineActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return CommandLineActivator.getInstance().getInjector(CommandLineActivator.ORG_REMUS_CMDLINE_COMMANDLINE);
	}
	
}
