/*
 * generated by Xtext
 */
package org.remus.cmdline;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CommandLineRuntimeModule extends org.remus.cmdline.AbstractCommandLineRuntimeModule {

}
