/*
 * generated by Xtext
 */
package org.remus.cmdline.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CommandLineUiModule extends org.remus.cmdline.ui.AbstractCommandLineUiModule {
	public CommandLineUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
