/*
 * generated by Xtext
 */
package org.remus.cmdline.ui.contentassist

import org.remus.cmdline.ui.contentassist.AbstractCommandLineProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class CommandLineProposalProvider extends AbstractCommandLineProposalProvider {
}
